# Generated by Django 4.2 on 2024-04-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociala2_app', '0005_alter_socialaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
